#!/usr/bin/env bash

# https://github.com/EnterpriseDB/repmgr/blob/master/doc/repmgrd-node-fencing.md

source /etc/pve/psql/profile

set -u
set -e

REPMGR_DB="repmgr"
REPMGR_USER="repmgr"

unquote(){
  quoted=$1
  type=${2:-'"'}
  unquoted=${quoted#*"$type"}
  unquoted=${unquoted%"$type"*}
  echo "$unquoted"
}

parse_repmgr_csv(){
  prefix=${1:-''}
  while IFS= read -r line; do
    name=$(unquote "$(echo "$line"| cut -d, -f1)")
    value=$(unquote "$(echo "$line"| cut -d, -f2-)")
    if [ -n "$name" ]; then
      name=$prefix$name
      name=${name// /_}
      name=${name^^}
      read -d"\0" "$name" <<<"$value"
    fi
  done
}

#Verify our role is ok
if ! repmgr node  check --role 2>/dev/null >/dev/null ; then
  echo "This role is not ready to be promoted"
  exit
fi


parse_repmgr_csv 'REPMGR_' <<< "$(repmgr node status --csv 2> /dev/null)" || true  


# 1. Promote this node from standby to primary

if [ "$REPMGR_ROLE" != "primary" ]; then
  repmgr standby promote --log-to-file
fi

# 2. Reconfigure pgbouncer instances
PSQL_PRIMARY_HOST=`psql -U postgres -tAc "select inet_server_addr();" "$REPMGR_CONNINFO"`
cat << EOF > "$PSQL_DATA/pgbouncer.database.ini"
[databases]
* = host=$PSQL_PRIMARY_HOST port=6432
EOF
sudo /usr/bin/bash "$PSQL_SCRIPTS/update_cluster_config"

psql -U postgres repmgr -tAc "SELECT conninfo FROM repmgr.nodes WHERE active = TRUE" | while read conninfo; do
  host=`psql -U postgres -tAc "select inet_server_addr();" "$conninfo"`
  if ! psql -U pgbouncer -tc "reload" -h $host pgbouncer > /dev/null; then
    echo "Error reloading pgbouncer at $host"
  fi
done

echo "Reconfiguration of pgbouncer complete"